[package]
edition = "2021"
name = "story"
publish = false
version = "0.1.0"

[dependencies]
anyhow.workspace = true
charts-rs = "0.3"
chrono = "0.4"
fake = { version = "2.10.0", features = ["dummy"] }
gpui.workspace = true
gpui-component.workspace = true
reqwest_client = { git = "https://github.com/huacnlee/zed.git", branch = "webview" }
rand = "0.8"
regex = "1"
rust-embed.workspace = true
serde = "1"
serde_json = "1"
unindent = "0.2.3"
raw-window-handle = { version = "0.6", features = ["std"] }

[lints]
workspace = true
